security:
    encoders:
        App\Entity\User:
            algorithm: sodium

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        main:
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /authentication_token
                username_path: email
                password_path: password
                success_handler: custom.jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - custom_jwt_token_authenticator

        api:
            pattern: ^/
            stateless: true
            anonymous: true
            provider: app_user_provider
            guard:
                authenticators:
                    - custom_jwt_token_authenticator

    access_control:
        - { path: ^/authentication_token$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]