
image: teqno/docker-image-symfony4-panther

stages:
  - tests

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: api
  MYSQL_USER: gitlab-ci
  MYSQL_ROOT_PASSWORD: root
  MYSQL_PASSWORD: password

panther:
  stage: tests
  services:
    - mysql:5.7
  before_script:
    - yarn install
    - yarn encore production
    - cp .env.test .env
    - cp phpunit.xml.test phpunit.xml
    - composer install
    - php bin/console doctrine:schema:update --force
  script:
    - ./bin/phpunit


#phpstan:
#  image: jakzal/phpqa
#  stage: tests
#  script: phpstan analyse --level 2 -c ./ci/phpstan.neon src
#  allow_failure: true
#
#php-metrics:
#  image: jakzal/phpqa
#  stage: tests
#  script: phpmetrics --report-html=var/php-metrics src
#  artifacts:
#    paths:
#      - var/php-metrics/
#  allow_failure: true
#
#php-phpmd:
#  image: jakzal/phpqa
#  stage: tests
#  script: phpmd src text ./ci/phpmd.xml
#  artifacts:
#    paths:
#      - var/phpmd.html
#  allow_failure: true
#
#php-deprecation-detector:
#  image: jakzal/phpqa
#  stage: tests
#  script:
#    - deprecation-detector check src vendor
#  allow_failure: true
#
#php-cs-fixer:
#  image: jakzal/phpqa
#  stage: tests
#  script:
#    - ci/php-cs-fixer.sh
#  artifacts:
#    paths:
#      - var/patch.diff
#    expire_in: 24 hrs
#    when: on_failure
#  allow_failure: true
